### ISSUE TITLE
OJS scrape does not work for pages with no 'citation' information

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1203]
https://tidsskrift.dk/aktualitet/article/view/111505

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fnielsen/projects/scholia/scholia/scrape/ojs.py", line 314, in <module>
    main()
  File "/home/fnielsen/projects/scholia/scholia/scrape/ojs.py", line 301, in main
    qs = paper_url_to_quickstatements(url)
  File "/home/fnielsen/projects/scholia/scholia/scrape/ojs.py", line 178, in paper_url_to_quickstatements
    paper = scrape_paper_from_url(url)
  File "/home/fnielsen/projects/scholia/scholia/scrape/ojs.py", line 223, in scrape_paper_from_url
    entry['date'] = _field_to_content('citation_date').replace('/', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by fnielsen** [comment]
There are also issues with language, see, e.g., https://tidsskrift.dk/politik/article/view/27594
